apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: foogra
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: DOCKERHUB_USERNAME/foogra-web:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: API_HOST
              value: "api"
            - name: API_PORT
              value: "8000"
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["SETUID", "SETGID"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
