#!/usr/bin/env bash
#
# Generates real secrets for local use and writes them where each tool
# expects them:
#   - ./.env               → docker-compose.yml (APP_KEY)
#   - k8s/31-api-secret.yaml / k8s/11-db-secret.yaml → replaces the
#     REPLACE_ME_* placeholders in place, so `kubectl apply -k k8s/` never
#     ships a real credential through git.
#
# Safe to re-run: it only touches REPLACE_ME_* placeholders and only
# creates .env if it does not already exist.
#
set -euo pipefail
cd "$(dirname "$0")/.."

rand_b64() { head -c "$1" /dev/urandom | base64 | tr -d '\n'; }

if [ ! -f .env ]; then
  app_key="base64:$(rand_b64 32)"
  cat > .env <<EOF
# Generated by scripts/gen-secrets.sh — local docker-compose secrets only.
# Never commit this file.
APP_KEY=${app_key}
EOF
  echo "wrote .env (APP_KEY)"
else
  echo ".env already exists, leaving it as-is"
fi

db_secret_file="k8s/11-db-secret.yaml"
api_secret_file="k8s/31-api-secret.yaml"

if [ -f "$db_secret_file" ] && grep -q "REPLACE_ME_mysql_password" "$db_secret_file"; then
  db_password="$(rand_b64 18)"
  root_password="$(rand_b64 18)"
  # base64 output can contain '/' — use a delimiter sed won't confuse with
  # the payload itself (same reasoning as the APP_KEY patch below).
  sed -i \
    -e "s#REPLACE_ME_mysql_password#${db_password}#g" \
    -e "s#REPLACE_ME_mysql_root_password#${root_password}#g" \
    "$db_secret_file"
  echo "patched ${db_secret_file}"
else
  echo "${db_secret_file}: already patched or not found, skipping"
fi

if [ -f "$api_secret_file" ] && grep -q "REPLACE_ME_app_key" "$api_secret_file"; then
  app_key_k8s="base64:$(rand_b64 32)"
  # APP_KEY contains '/' and '+' from base64 — use a delimiter sed won't
  # confuse with the payload itself.
  sed -i "s#REPLACE_ME_app_key#${app_key_k8s}#g" "$api_secret_file"
  echo "patched ${api_secret_file}"
else
  echo "${api_secret_file}: already patched or not found, skipping"
fi

echo "done."
